from cohere.classify import Example

goodExamples = [
    Example("Will stand the test of time.", "positive"),
    Example("First black manager hired.", "positive"),
    Example("Will be updated to be better.", "positive"),
    Example("Not as bad as you think.", "positive"),
    Example("Expands to new horizons", "positive"),
    Example("Found innocent and aqcuitted", "positive"),
    Example("Fully supported with excellent customer service", "positive"),
    Example("State-of-the-art.", "positive"),
    Example("Donates millions to charity.", "positive"),
    Example("Invests in sustainable technologies.", "positive"),
    Example("Generates dividends for investors.", "positive"),
    Example("Stocks rise.", "positive"),
    Example("Environmentally conscious.", "positive"),
    Example("Improved safety allows for safe operations.", "positive"),
    Example("Saves lives through innovative use of technologies.", "positive"),
    Example("Hires many new employees.", "positive"),
    Example("Bull market.", "positive"),
    Example("Combats climate change by investing in entrepreneurs.", "positive"),
    Example("An industry standard that is important.", "positive"),
    Example("Brand new technology.", "positive"),
    Example("Researches new avenues in revenue generation.", "positive"),
    Example("Defines an era with its amazing work ethic.", "positive"),
    Example("What would life be like without it? Unimaginable.", "positive"),
    Example("Sweet new deals on the latest tech.", "positive"),
    Example("Lower prices lead to record profits.", "positive"),
]
